### ISSUE TITLE
Resultant Image

### ISSUE THREAD

**Issue by ghost** [paladin-t/framepacker#3]
I just ran the program on a series of randomly generated images.
This was the result.

![output](https://user-images.githubusercontent.com/4486381/86391372-56a83280-bc5f-11ea-91ad-1f7e7dbecad8.png)

There's a lot of empty space here. Is this expected?

**Comment by paladin-t** [comment]
I added back the '-s' option, please try something like `-s 256x256` to hint for constraint.

**Comment by ghost** [comment]
Thanks. I ended up rolling my own that's mipmap-friendly.
